[package]
name = "crypto-tk-rs"
version = "0.1.0"
authors = ["OpenSSE Project", "Raphael Bost <raphael_bost@alumni.brown.edu>"]
edition = "2018"

description = "OpenSSE's Rust cryptographic toolkit"
homepage = "https://opensse.github.io/"
repository = "https://github.com/OpenSSE/crypto-tk-rs/"
readme = "README.md"
categories = ["cryptography"]
keywords = ["cryptography", "crypto-library"]
license = "AGPL-3.0-or-later"
license-file = "LICENSE"

[dependencies]
