[package]
name = "crypto-tk-rs"
version = "0.1.0"
authors = ["OpenSSE Project", "Raphael Bost <raphael_bost@alumni.brown.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
