name: CI

on: push

jobs:
  setup:
    name: Set environment Up
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Clone repo
        uses: actions/checkout@v2
      - run: cargo build --release --all-features
      - run: cargo test --release --all-features
  # build:
  #   name: Build the crypto-tk-rs library
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: cargo build --release --all-features
  # test:
  #   name: Test the crypto-tk-rs library
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: cargo test --release --all-features
